app = 'tradingview-telegram-bot-xdhm5w'
primary_region = 'jnb'

[build]

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
